# -*- coding: utf-8 -*-
"""Python Audio Separator for Colab | Official (2)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NZbreNoOy6ZASLQB_jIaXLuDLYgwiYhr

# **AUDIO SEPARATOR Colab**

- colab made by **[BF667](https://github.com/BF667-IDLE)**
- Python Audio Separator by **[Beveradb](https://github.com/beveradb)**



- UVR5  by **[Anjok07](https://github.com/Anjok07)**

- yt_dlp by **[yt_dlp](https://github.com/yt_dlp)**


Special thanks to:

* [Politrees](https://github.com/Politrees) and [Eddycrack864](https://github.com/Eddycrack864) thier code helping me so much

<big> **Note:** you can see by example i give to u


Want more features?


Open [issue](https://github.com/BF667/audio-separator-colab-work/issues) on my official work repo

<big> **Changelog:**

- Fix numpy bug on newer colab. newer colab is worse :(
- Update fix
- ytdlp
- improving all colab code
- uv pip installation adaptation
 - Update colab cell
"""

# Commented out IPython magic to ensure Python compatibility.

# @title # **Installation Setup**
from IPython.display import clear_output
import codecs

import os
import shutil
import sys
from pathlib import Path

url = "https://github.com/BF667/audio-separator-colab-work.git"

repopath = codecs.decode('HIE5/erdhverzragf.gkg', 'rot_13')
repath = codecs.decode('HIE5', 'rot_13')


print("Installing...")



# Fix: Explicitly reinstall onnxruntime-gpu to resolve ModuleNotFoundError
!uv pip install --force-reinstall onnxruntime-gpu
!pip install uv pyngrok > /dev/null 2>&1
!git clone {url} {repath}
!uv pip install -r $repopath > /dev/null 2>&1
os.system("pip install demucs")
!apt-get update > /dev/null 2>&1
!pip install aria2 > /dev/null 2>&1
!mkdir models > /dev/null 2>&1
!mkdir temp > /dev/null 2>&1
!aria2c > /dev/null 2>&1
!apt-get install -y libcudnn8 > /dev/null 2>&1


#@markdown ---

!aria2c https://huggingface.co/NeoPy/UVR/resolve/main/drumsep/model.th -o models/drumsep.th

# %cd /content/UVR5

# Commented out IPython magic to ensure Python compatibility.
# 
# #@title **fixes 2 march update**
# 
# 
# %%capture
# 
# #@markdown ---
# 
# 
# #@markdown #### **NOTE**: if runtime restart, it mean the fix works :D
# !uv pip install numpy==2.3.5 -q
# !uv pip install numba==0.63.1
# 
# 
# #  Force runtime restart (cleaner than SIGKILL)
# import os
# os.kill(os.getpid(), 9)

#@title Leaderboard

list_model = "vocals" #@param ["vocals", "instrumental", "reverb", "echo", "noise", "crowd", "dry", "aspiration", "male", "woodwinds", "kick", "drums", "bass", "guitar", "piano", "other"]

!audio-separator -l --list_filter={list_model}

# @title YouTube Audio Downloader (MP3)
from IPython.display import Audio, display
import yt_dlp
import os

youtube_url = "https://youtu.be/f-ml10dFHlA?si=nEllvsC6ltZIUKbt" # @param {type:"string"}

#@markdown ---


#output_filename = "ThanksForYourTime" # @param {type:"string"}

# Create audios directory if it doesn't exist
if not os.path.exists("audios"):
    os.makedirs("audios")

# Options for yt-dlp to download only audio and convert to mp3
ydl_opts = {
    'format': 'bestaudio/best',
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredquality': '192',
    }],
    'outtmpl': "audios/%(title)s",
    'quiet': False, # Suppress yt-dlp output
    'no_warnings': True, # Suppress yt-dlp warnings
}

try:
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        result = ydl.extract_info(youtube_url, download=True)
        download_path = ydl.prepare_filename(result, outtmpl='audios/%(title)s.mp3')
        print(f"Successfully downloaded: {result.get('title', 'Audio')}.")

except Exception as e:
    print(f"An error occurred: {e}")
    print("Please ensure the YouTube URL is valid and accessible.")

# @title Basic Audio Separation



from audio_separator.separator import Separator
import os
import logging
# User inputs for audio file and model
audio_file = "/content/audios/No me case mi madre.opus"  # @param {type:"string"}

#@markdown ---
model_name = "vocals_mel_band_roformer.ckpt"  # @param {type:"string"}

# Initialize the Separator class
separator = Separator(log_level=logging.WARNING)

# Load the specified model (defaults to model_mel_band_roformer_ep_3005_sdr_11.4360.ckpt if empty)
separator.load_model(model_filename=model_name if model_name else None)

output_names = {
    "Vocals": "vocals_output",
    "Instrumental": "instrumental_output",
}


# Check if the audio file exists
if not os.path.exists(audio_file):
    print(f"Error: Audio file '{audio_file}' not found. Please upload it to Colab.")
else:
    # Perform the separation
    output_files = separator.separate(audio_file, output_names)
    print(f"Separation complete! Output file(s): {' '.join(output_files)}")

# @title Play Audio

from IPython.display import Audio, display
import os

#@markdown Specify the path to your audio file.
audio_file_path = "/content/vocals_output.wav" # @param {type:"string"}

if os.path.exists(audio_file_path):
  display(Audio(audio_file_path))
else:
  print(f"Error: Audio file not found at {audio_file_path}")